#!/bin/bash
[ "${debug}" = "true" ] && set -x

function hlp(){
( cat << EOF
del will delete  CONTAINERS - even if they are running (using the --force flag on lxc-destroy)
EOF
)
}

function doc(){
( cat << EOF
$(hlp)
EOF
)
}

function del(){
    for CONTAINER in ${CONTAINERS}
    do
        SUFFIX=${CONTAINER##*-}
        [ ! "${SUFFIX}" = "model" ] && lxc-destroy --force ${CONTAINER}
    done
}

$CMD
