#!/bin/bash
[ "${debug}" = "true" ] && set -x

function hlp(){
( cat << EOF
    onn starts all containers on the command line
EOF
)
}

function doc(){
( cat << EOF
$(hlp)
EOF
)
}

function onn(){
    for CONTAINER in ${CONTAINERS}
    do
        SUFFIX=${CONTAINER##*-}
        [ ! "${SUFFIX}" = "model" ] && lxc-start ${CONTAINER}
    done
}

$CMD
