#!/bin/bash
[ "${debug}" = "true" ] && set -x

function model(){
    export CONTAINER=${PREFIX}-model
    lxc-destroy -f ${CONTAINER}
    lxc-create --name ${CONTAINER} -t download -- ${LINUX}  >> ${logfile} 2>&1
    lxc-start --name ${CONTAINER}
    ${ELECSEE} net ${CONTAINER}
    CONTEXT=model /bin/bash ${ELECSEE_SCRIPTS}/ssh
    CONTEXT=model /bin/bash ${ELECSEE_SCRIPTS}/${PREFIX}
}

function instance(){
    lxc-stop --name ${PREFIX}-model
    lxc-destroy -f --name ${CONTAINER}
    lxc-copy --name ${PREFIX}-model --newname ${CONTAINER}
    lxc-start --name ${CONTAINER}
    ${ELECSEE} net ${CONTAINER}
    ${ELECSEE} hst
}


for CONTAINER in ${CONTAINERS}
do
    export CONTAINER
    export SUFFIX=${CONTAINER##*-}
    export PREFIX=${CONTAINER%-${SUFFIX}}
    ${ELECSEE} lst | grep '^'${PREFIX}-model' ' >> ${logfile} 2>&1 || (
        echo building model
        (model)
    )
    echo building ${CONTAINER}
    (instance >> ${logfile} 2>&1)
    CONTEXT=instance /bin/bash ${ELECSEE_SCRIPTS}/ssh
    CONTEXT=instance /bin/bash ${ELECSEE_SCRIPTS}/${PREFIX}
    lxc-stop --name ${CONTAINER}
    lxc-start --name ${CONTAINER}
done

# transfer public key to all containers
# remove stale keys from known_hosts
# make ssh and accept this host

