#!/bin/bash
[ "${debug}" = "true" ] && set -x
. ${ELECSEE} # to get argspec array
export logfile=/dev/stdout

function hlp(){
( cat << EOF
    doc writes elecsees documentation
EOF
)
}



function doc(){
(
cat << EOF
# ELECSEE

This is the documentation of elecsee, a utility for easing my use of lxc on ubuntu.

It can do three things that I missed:

* put containers in /etc/hosts automatically
* make containers autostartable using systemd units
* expose TCP and UDP services from containers on the primary interface of the host

elecsee has a set of subcommands that takes parameters, but no flags - below is a summary
EOF
)

for ix in $( echo ${!_ARGSPEC[*]} | sort)
do
    echo
    echo "##$ix"
    echo
    if [ "${_ARGSPEC[$ix]}" = "" ]
    then
        echo "**elecsee $ix** takes no arguments"
        echo
    else
        echo "**elecsee $ix** takes the following arguments: ${_ARGSPEC[$ix]}"
        echo
    fi
    
    [ ! "$ix" = "doc" ] && CMD=doc ${ELECSEE_COMMANDS}/elecsee-${ix} | sed 's/^ */\n/'
    
done
}


$CMD
