#!/bin/bash
[ "${debug}" = "true" ] && set -x
export SOURCE_ONLY=yes
export logfile=/dev/stdout
. ${ELECSEE} # to get argspec array


function hlp(){
cat << EOF

elecsee
-------

elecsee has a set of 3 letter subcommands that takes parameters, but no flags - below is a summary

EOF

for ix in $( echo ${!_ARGSPEC[*]} | sort)
do
    echo "$ix"
    if [ "${_ARGSPEC[$ix]}" = "" ]
    then
        echo "    elecsee $ix takes no arguments"
    else
        echo "    elecsee $ix takes the following arguments: ${_ARGSPEC[$ix]}"
    fi
    
    [ ! "$ix" = "hlp" ] && CMD=hlp ${ELECSEE_COMMANDS}/elecsee-${ix} | sed 's/^/    /'
    
done
}

function doc(){
cat << EOF
The following example will print out the help text

    elecsee hlp
EOF
}

$CMD
