#!/bin/bash
[ "${debug}" = "true" ] && set -x

function hlp(){
echo add users $USO and $USS, public certs and ssh capabilites to the model
}

function doc(){
cat << EOF
Two users are created ($USO and $USS), the first one is an ordinary user, the latter has sudo password-less sudo capabilities

You are equipped with a special certificate (~/.ssh/elecsee.pub) if you dont have it in advance and the container-users ($USO and $USS) are both given the public key for this certificate, which enables you to log in to the containers without password (which these users do not have)

This script assumes that 'hst' has been called while this container is running, since it will end it's work by trying to ssh into the named container
EOF
}

function elecsee-cert(){
    su -l -c 'ssh-keygen -b 2048 -t rsa -C elecsee -f ~/.ssh/elecsee' $ME
}

function _ssh(){
[ -f /home/${ME}/.ssh/elecsee.pub ] || (elecsee-cert)
(cat << EOF
[ "${debug}" = "true" ] && set -x
apt update
apt install -y ssh openssh-server sudo
adduser $USS --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password
adduser $USO --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password
su -l -c 'mkdir ~/.ssh; chmod 700 ~/.ssh' $USS 
su -l -c 'mkdir ~/.ssh; chmod 700 ~/.ssh' $USO 
su -l -c 'ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa' $USS 
su -l -c 'ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa' $USO
echo $USS' ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
echo ${CONTAINER} > /etc/hostname
EOF
) | ( 
    [ "$PRIVILEGED" = "true" ] \
    && lxc-attach --name ${CONTAINER} \
    || sudo -u ${ME} lxc-attach --name ${CONTAINER}
) >> ${logfile} 2>&1

[ "$PRIVILEGED" = "true" ]  && (
    cat /home/${ME}/.ssh/elecsee.pub | lxc-attach --name ${CONTAINER} /bin/sh -- -c '/bin/cat > /home/'$USO'/.ssh/authorized_keys' 
    cat /home/${ME}/.ssh/elecsee.pub | lxc-attach --name ${CONTAINER} /bin/sh -- -c '/bin/cat > /home/'$USS'/.ssh/authorized_keys'
) || (
    cat /home/${ME}/.ssh/elecsee.pub | sudo -u ${ME} lxc-attach --name ${CONTAINER} /bin/sh -- -c '/bin/cat > /home/'$USO'/.ssh/authorized_keys' 
    cat /home/${ME}/.ssh/elecsee.pub | sudo -u ${ME} lxc-attach --name ${CONTAINER} /bin/sh -- -c '/bin/cat > /home/'$USS'/.ssh/authorized_keys'
)
sudo su -l -c "ssh-keygen -f /home/${ME}/.ssh/known_hosts -R ${CONTAINER}" $ME >> ${logfile} 2>&1
sudo su -l -c "ssh -o PasswordAuthentication=no -o CheckHostIP=no -o StrictHostKeyChecking=no $USS@${CONTAINER} :" $ME >> ${logfile} 2>&1
sudo su -l -c "ssh -o PasswordAuthentication=no -o CheckHostIP=no -o StrictHostKeyChecking=no $USO@${CONTAINER} :" $ME >> ${logfile} 2>&1

}

function ssh(){
    for CONTAINER in ${CONTAINERS}
    do
        export CONTAINER
        ${ELECSEE} lst | grep '^'${CONTAINER}'.*false\W*$' && PRIVILEGED=true || PRIVILEGED=false
        export PRIVILEGED
        _ssh
    done
}


$CMD

