#!/bin/bash
[ "${debug}" = "true" ] && set -x

function hlp(){
( cat << EOF
    net awaits until all containers on the command line has network connection (this usually takes app. 4 seconds
EOF
)
}

function doc(){
( cat << EOF
$(hlp)
EOF
)
}

function _net(){
(
cat << EOF
(
    echo wait for container to start > /dev/stderr
    while true
    do
        ping -c 1 ubuntu.com && break
        sleep 1
    done 
)
EOF
) | sudo lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}

function net(){
    for CONTAINER in ${CONTAINERS}
    do
        _net
    done
}


$CMD
