#!/bin/bash
[ "${debug}" = "true" ] && set -x

function hlp(){
( cat << EOF
off stops all containers on the command line
EOF
)
}

function doc(){
( cat << EOF
$(hlp)
EOF
)
}

function off(){
    for CONTAINER in ${CONTAINERS}
    do
        sudo lxc-stop --name ${CONTAINER}
    done
}

$CMD
