#!/bin/bash
[ "${debug}" = "true" ] && set -x
export SOURCE_ONLY=yes
. ${ELECSEE} # to get argspec array
export logfile=/dev/stdout

function hlp(){
( cat << EOF
doc writes elecsees documentation
EOF
)
}



function doc(){
(
cat << EOF
# ELECSEE

This is the documentation of elecsee, a utility for easing my use of lxc on ubuntu.

It can do three things that I missed:

* put containers in /etc/hosts automatically
* make containers autostartable using systemd units
* expose TCP and UDP services from containers on the primary interface of the host

This is not a docker replacement. Lots can go wrong when building the containers, using bash -x \$(which elecsee) should turn on full debugging

Elecsee has a set of subcommands that takes parameters, but no flags - below is a summary
EOF
)

for ix in $( printf "%s\n" ${!_ARGSPEC[*]} | sort)
do
    echo
    echo "## $ix"
    echo
    if [ "${_ARGSPEC[$ix]}" = "" ]
    then
        echo "**elecsee $ix** takes no arguments"
        echo
    else
        echo "**elecsee $ix** takes the following arguments: ${_ARGSPEC[$ix]}"
        echo
    fi
    
    lix=$(realpath ${ELECSEE_COMMANDS}/elecsee-$ix)
    lix=${lix##*elecsee-}
    if [ "$ix" = "$CMD" ] 
    then
        echo "you are watching the output of this command"
    elif [ "$lix" = "$ix" ]
    then
        CMD=doc ${ELECSEE_COMMANDS}/elecsee-${ix} 
    else
        echo "this is the inverse of the command '"$lix"' - and is documented there"
    fi
    
done
}


$CMD
