#!/bin/bash
[ "${debug}" = "true" ] && set -x

function hlp(){
( cat << EOF
onn starts all containers on the command line
EOF
)
}

function doc(){
( cat << EOF
$(hlp)
EOF
)
}

function onn(){
    for CONTAINER in ${CONTAINERS}
    do
        ${ELECSEE} lst | grep '^'${CONTAINER}'.*false\W*$' && PRIVILEGED=true || PRIVILEGED=false
        if [ "${PRIVILEGED}" = "true" ]
        then
            lxc-start --name ${CONTAINER}
        else
            sudo -u ${ME} lxc-start --name ${CONTAINER}
        fi
    done
}

$CMD
