#!/bin/bash
[ "${debug}" = "true" ] && set -x

function hlp(){
( cat << EOF
off stops all containers on the command line
EOF
)
}

function doc(){
( cat << EOF
$(hlp)
EOF
)
}

function off(){
    for CONTAINER in ${CONTAINERS}
    do
        ${ELECSEE} lst | grep '^'${CONTAINER}'.*false\W*$' && PRIVILEGED=true || PRIVILEGED=false
        if [ "${PRIVILEGED}" = "true" ]
        then
            lxc-stop --name ${CONTAINER}
        else
            sudo -u ${ME} lxc-stop --name ${CONTAINER}
        fi
    done
}

$CMD
