#!/bin/bash
[ "${debug}" = "true" ] && set -x
export SOURCE_ONLY=yes
export logfile=/dev/stdout
. ${ELECSEE} # to get argspec array


function hlp(){
cat << EOF

elecsee
-------

elecsee has a set of 3 letter subcommands that takes parameters, but no flags - below is a summary

EOF

for ix in $( echo ${!_ARGSPEC[*]} | sort)
do
    echo "$ix"
    if [ "${_ARGSPEC[$ix]}" = "" ]
    then
        echo "    takes no arguments"
    else
        echo "    arguments: ${_ARGSPEC[$ix]}"
    fi
    lix=$(realpath ${ELECSEE_COMMANDS}/elecsee-$ix)
    lix=${lix##*elecsee-}
    if [ "$ix" = "$CMD" ] 
    then
        echo "    you are watching the output of this command"
    elif [ "$lix" = "$ix" ]
    then
        CMD=hlp ${ELECSEE_COMMANDS}/elecsee-${ix} | sed 's/^/    /'
    else
        echo "    this is the inverse of the command '"$lix"' - and is documented there"
    fi
    
done
}

function doc(){
cat << EOF
The following example will print out the help text

    elecsee hlp
EOF
}

$CMD
