#!/bin/bash
[ "${debug}" = "true" ] && set -x

function hlp(){
( cat << EOF
del will delete  CONTAINERS - even if they are running (using the --force flag on lxc-destroy)
EOF
)
}

function doc(){
( cat << EOF
$(hlp)
EOF
)
}

function del(){
    for CONTAINER in ${CONTAINERS}
    do
        ${ELECSEE} lst | grep '^'${CONTAINER}'.*false\W*$' && PRIVILEGED=true || PRIVILEGED=false
        if [ "${PRIVILEGED}" = "true" ]
        then
            lxc-destroy -force --name ${CONTAINER}
        else
            sudo -u ${ME} lxc-destroy --force --name ${CONTAINER}
        fi
    done
}

$CMD
