#!/bin/bash
[ "${debug}" = "true" ] && set -x

function hlp(){
cat << EOF
ensures that elecsee uses a danish mirror for archive.ubuntu.com
EOF
}

function model(){
[ "${debug}" = "true" ] && set -x
(hlp)
(cat << EOF
[ "${debug}" = "true" ] && set -x
apt install -y sed
sed -i 's#http://archive.ubuntu.com/ubuntu#http://mirror.netsite.dk/ubuntu/archive/#' /etc/apt/sources.list
apt update
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




function instance(){
[ "${debug}" = "true" ] && set -x
(cat << EOF
[ "${debug}" = "true" ] && set -x
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




$CONTEXT
