#!/bin/bash
# has debug, logfile, container, prefix and suffix
[ "${debug}" = "true" ] && set -x


[ "${suffix}" = "model" ] && echo add java 8 to model - this will take some time && (
( 
cat << EOF
[ "${debug}" = "true" ] && set -x
add-apt-repository ppa:webupd8team/java
apt-get update
echo debconf shared/accepted-oracle-license-v1-1 select true | \
  sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | \
  sudo debconf-set-selections
apt-get --quiet install -y oracle-java8-installer 
EOF
) | sudo lxc shell  ${container} >>${logfile} 2>&1
) >> ${logfile} 2>&1

[ ! "${suffix}" = "model" ] && echo initialize java && (
( 
cat << EOF
:
EOF
) | sudo lxc shell  ${container} >>${logfile} 2>&1
) >> ${logfile} 2>&1
