#!/bin/bash

function doc(){
cat << EOF
adds a little jay to the container
EOF
}


function model(){
(. ${ELECSEE_SCRIPTS}/python)
(cat << EOF
[ "${debug}" = "true" ] && set -x
apt-get --quiet install -y curl wget git git-flow 
sudo su -l -c 'ssh-keygen -b 2048 -t rsa -f ~/.ssh/jaysltr_rsa' $USS
sudo su -l -c 'ssh-keygen -b 2048 -t rsa -f ~/.ssh/jayrnnr_rsa' $USS
sudo su -l -c 'ssh-keygen -b 2048 -t rsa -f ~/.ssh/jayfolr_rsa' $USS
sudo su -l -c 'ssh-keygen -b 2048 -t rsa -f ~/.ssh/jaysolr_rsa' $USS
sudo su -l -c 'ssh-keygen -b 2048 -t rsa -f ~/.ssh/jayviwr_rsa' $USS
sudo su -l -c 'ssh-keygen -b 2048 -t rsa -f ~/.ssh/jaynews_rsa' $USS
sudo su -l -c 'ssh-keygen -b 2048 -t rsa -f ~/.ssh/jaytwit_rsa' $USS
sudo su -l -c 'ssh-keygen -b 2048 -t rsa -f ~/.ssh/jaygeon_rsa' $USS
sudo su -l -c 'ssh-keygen -b 2048 -t rsa -f ~/.ssh/jaypern_rsa' $USS
sudo su -l -c 'ssh-keygen -b 2048 -t rsa -f ~/.ssh/jayprxy_rsa' $USS
sudo su -l -c 'ssh-keygen -b 2048 -t rsa -f ~/.ssh/jaysqla_rsa' $USS
sudo su -l -c 'ssh-keygen -b 2048 -t rsa -f ~/.ssh/jaymaga_rsa' $USS
EOF
) | sudo -u ${ME} lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




function write-github(){
cat << EOF
    mkdir $1 || exit
    cd $1
    git init
    git remote add origin git@github.com:gardsted/$1.git; 
    git config core.sshCommand "ssh -i ~/.ssh/$1_rsa -o PasswordAuthentication=no -o CheckHostIP=no -o StrictHostKeyChecking=no"
    git pull origin development
    git pull origin master
    git branch development
    git checkout development
    python3 -m venv venv
    venv/bin/pip install -r requirements.txt
EOF

}

function instance(){
(cat << EOF
[ "${debug}" = "true" ] && set -x
sudo su -l -c '($(write-github jaysltr))' $USS
sudo su -l -c '($(write-github jayrnnr))' $USS
sudo su -l -c '($(write-github jayfolr))' $USS
sudo su -l -c '($(write-github jaysolr))' $USS
sudo su -l -c '($(write-github jayviwr))' $USS
sudo su -l -c '($(write-github jaynews))' $USS
sudo su -l -c '($(write-github jaytwit))' $USS
sudo su -l -c '($(write-github jaygeon))' $USS
sudo su -l -c '($(write-github jaypern))' $USS
sudo su -l -c '($(write-github jayprxy))' $USS
sudo su -l -c '($(write-github jaysqla))' $USS
sudo su -l -c '($(write-github jaymaga))' $USS
EOF
) | sudo -u ${ME} lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}


$CONTEXT
