#!/bin/bash
export LINUX="--dist=ubuntu --release=bionic --arch=amd64"


function doc(){
cat << EOF
makes a php-apache-thing
EOF
}




function model(){
(doc)
(cat << EOF
[ "${debug}" = "true" ] && set -x
rm /etc/localtime
ln -s /usr/share/zoneinfo/Europe/Copenhagen /etc/localtime
apt update
apt-get install -y ssh curl apache2 php php-pear php-fpm php-dev php-zip php-xml libapache2-mod-php php-mysql php-curl mysql-server
EOF
) | sudo -u ${ME} lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}


function instance(){
(cat << EOF
[ "${debug}" = "true" ] && set -x
systemctl restart apache2
echo '<?php phpinfo(); ?>' > /var/www/html/info.php
EOF
) | sudo -u ${ME} lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




$CONTEXT
