#!/bin/bash

function doc(){
cat << EOF
adds a little mmcse to the container
EOF
}


function model(){
(. ${ELECSEE_SCRIPTS}/python)
(cat << EOF
[ "${debug}" = "true" ] && set -x
apt-get --quiet install -y curl wget git git-flow default-jre
sudo su -l -c 'ssh-keygen -b 2048 -t rsa -f ~/.ssh/mmcse_rsa' $USS
EOF
) | sudo -u ${ME} lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




function write-github(){
cat << EOF
    mkdir $1 || exit
    cd $1
    git init
    git remote add origin git@github.com:gardsted/$1.git; 
    git config core.sshCommand "ssh -i ~/.ssh/$1_rsa -o PasswordAuthentication=no -o CheckHostIP=no -o StrictHostKeyChecking=no"
    git pull origin development
    git pull origin master
    git branch development
    git checkout development
    python3 -m venv venv
EOF

}

function instance(){
(cat << EOF
[ "${debug}" = "true" ] && set -x
sudo su -l -c '($(write-github mmcse))' $USS
EOF
) | sudo -u ${ME} lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
echo now ssh into container, cd mmcse and run src_setup/download.sh after putting in git-ssh-key
}


$CONTEXT
