#!/bin/bash



function doc(){
cat << EOF
adds mongodb community edition to container
EOF
}



function model(){
echo add mongodb to model
(cat << EOF
[ "${debug}" = "true" ] && set -x
apt-get install -y gnupg
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
apt-get update -y
apt-get install -y mongodb-org mongodb-org-server mongodb-org-mongos mongodb-org-tools
systemctl enable mongod
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




function instance(){
(cat << EOF
[ "${debug}" = "true" ] && set -x
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




$CONTEXT


