#!/bin/bash


function model(){
echo add metasploit to model
(cat << EOF
apt-get install -y curl
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall &&  bash -x ./msfinstall
  msfupdate
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




function instance(){
echo initialize metasploit
(cat << EOF
[ "${debug}" = "true" ] && set -x
su -l -c'/opt/metasploit-framework/bin/msfdb init' $USS
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




$CONTEXT
