#!/bin/bash

function doc(){
cat << EOF
adds mariadb to container
EOF
}




function model(){
(cat << EOF
[ "${debug}" = "true" ] && set -x
apt update
apt install -y mariadb-server-10.1
EOF
) | sudo -u ${ME} lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




function instance(){
(cat << EOF
[ "${debug}" = "true" ] && set -x
sed 's/\(bind-address[[:space:]]*=\).*/\1 0.0.0.0/g' -i /etc/mysql/mariadb.conf.d/50-server.cnf 
EOF
) | sudo -u ${ME} lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}


# CREATE USER 'clint'@'10.0.3.%' IDENTIFIED BY 'password';
# GRANT ALL PRIVILEGES ON *.* TO 'clint'@'10.0.3.%' WITH GRANT OPTION;


$CONTEXT


