#!/bin/bash
# has debug, logfile, container, prefix and suffix
[ "${debug}" = "true" ] && set -x


function model(){
echo add java 8 to model - this will take some time
(cat << EOF
[ "${debug}" = "true" ] && set -x
apt-get -y install software-properties-common
add-apt-repository -y ppa:webupd8team/java
apt-get update -y
echo debconf shared/accepted-oracle-license-v1-1 select true | \
  debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | \
  debconf-set-selections
apt-get --quiet install -y oracle-java8-installer 
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




function instance(){
:
}




$CONTEXT

