#!/bin/bash

function hlp(){
cat << EOF
adds python3 to the model
EOF
}

function model(){
(hlp)
(cat << EOF
[ "${debug}" = "true" ] && set -x
apt-get --quiet install -y python3 python3-pip  python3-venv
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




function instance(){
(cat << EOF
[ "${debug}" = "true" ] && set -x

EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




$CONTEXT
