#!/bin/bash
export LINUX="--dist=ubuntu --release=xenial --arch=amd64"

function doc(){
cat << EOF
adds salt minion to the container
EOF
}


function model(){
(. ${ELECSEE_SCRIPTS}/python)
(cat << EOF
[ "${debug}" = "true" ] && set -x
wget -O - https://repo.saltstack.com/py3/ubuntu/16.04/amd64/2019.2/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
echo deb http://repo.saltstack.com/py3/ubuntu/16.04/amd64/2019.2 xenial main  >> /etc/apt/sources.list.d/saltstack.list
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




function instance(){
(cat << EOF
[ "${debug}" = "true" ] && set -x
rm /etc/ssh/*_key*
ssh-keygen -A
sudo apt-get update
apt install -y salt-minion
systemctl stop salt-minion
echo ${CONTAINER}  > /etc/salt/minion_id
sed -i 's/^#* *master: .*$/master: saltma-1/' /etc/salt/minion
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




$CONTEXT
