#!/bin/bash
export LINUX="--dist=ubuntu --release=xenial --arch=amd64"

function doc(){
cat << EOF
adds salt master to the container
EOF
}


function model(){
(. ${ELECSEE_SCRIPTS}/python)
(cat << EOF
[ "${debug}" = "true" ] && set -x
wget -O - https://repo.saltstack.com/py3/ubuntu/16.04/amd64/2019.2/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
echo deb http://repo.saltstack.com/py3/ubuntu/16.04/amd64/2019.2 xenial main  >> /etc/apt/sources.list.d/saltstack.list
sudo apt-get update
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




function instance(){
(cat << EOF
[ "${debug}" = "true" ] && set -x
sudo apt-get update
apt install -y salt-master 
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}

# then
# sudo salt '*' cmd.run 'wall hello world'
# sudo salt -L saltmi-1 cmd.run 'wall hello world'
# sudo salt '*' cmd.run_stderr "ls -l | awk '{print \$2}'"
# 
# State x.sls: what is installed when minion has gotten the 'x'
# Pillar: configuration for hosts
#
# Several states can be incluenced by same pillar - i think there is a mask inside the pillar
#
#
#
#



$CONTEXT
