#!/bin/bash

function doc(){
cat << EOF
builds db-preservation-toolkit to container
EOF
}


function model(){
(. ${ELECSEE_SCRIPTS}/oracle-java)
(cat << EOF
[ "${debug}" = "true" ] && set -x
apt update
apt install -y git maven wget
sudo su -l -c 'git clone https://github.com/keeps/db-preservation-toolkit.git' $USS
wget http://central.maven.org/maven2/org/apache/maven/wagon/wagon-http/2.8/wagon-http-2.8-shaded.jar
cp wagon-http-2.8-shaded.jar /usr/share/maven
sudo su -l -c 'cp db-preservation-toolkit/.travis/maven_settings.xml db-preservation-toolkit' $USS
sudo su -l -c '(cd db-preservation-toolkit ; mvn -gs maven_settings.xml package)' $USS
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




function instance(){
(cat << EOF
[ "${debug}" = "true" ] && set -x
sudo su -l -c '(cd db-preservation-toolkit ; git pull)' $USS
sudo su -l -c '(cd db-preservation-toolkit ; mvn -gs maven_settings.xml package)' $USS
# this will not work before updating the maven_settings with oracle username
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}



$CONTEXT
