#!/bin/bash
SOLR=7.5.0

/bin/bash $(dirname $0)/java


function model(){
echo add java 8 to model - this will take some time
(cat << EOF
[ "${debug}" = "true" ] && set -x
apt-get --quiet install -y curl wget
wget http://apache.40b.nl/lucene/solr/${SOLR}/solr-${SOLR}-src.tgz
tar -zxvf solr-${SOLR}-src.tgz
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




function instance(){
(cat << EOF
[ "${debug}" = "true" ] && set -x

EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




$CONTEXT
