#!/bin/bash
[ "${debug}" = "true" ] && set -x

function hlp(){
echo adds texttv to model
}


function model(){
(hlp)
/bin/bash -e ${ELECSEE_SCRIPTS}/python
(cat << EOF
apt install -y ffmpeg ffmpeg-doc imagemagick git git-flow python3-venv curl
su -l -c 'git clone -b development https://github.com/gardsted/texttv' $USS
su -l -c 'cd texttv && python3 -m venv venv && venv/bin/pip install -r requirements.txt' $USS
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




function instance(){
(cat << EOF
su -l -c 'cd texttv && git pull && venv/bin/pip install -r requirements.txt --upgrade' $USS
su -l -c 'curl https://raw.githubusercontent.com/fabricjs/fabric.js/master/dist/fabric.js -o texttv/texttv/static/fabric.js' $USS
su -l -c 'curl https://ajax.googleapis.com/ajax/libs/angularjs/1.7.5/angular.js -o texttv/texttv/static/angular.js' $USS
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1

}


$CONTEXT

