#!/bin/bash
set -x
[ "${DEBUG}" = "true" ] && set -x
export PRIVILEGED=false


function hlp(){
echo adds texttv to model
}


function model(){
(hlp)
/bin/bash -e ${ELECSEE_SCRIPTS}/python
(cat << EOF
[ "${debug}" = "true" ] && set -x
apt install -y git git-flow python3-venv
su -l -c 'git clone -b development https://github.com/gardsted/texttv' $USS
su -l -c 'cd texttv && python3 -m venv venv && venv/bin/pip install -r requirements.txt' $USS
EOF
) | lxc-attach --name ${CONTAINER}
}




function instance(){
(cat << EOF
[ "${debug}" = "true" ] && set -x
su -l -c 'cd texttv && git pull && venv/bin/pip install -r requirements.txt --upgrade' $USS
EOF
) | lxc-attach --name ${CONTAINER}

}

${CONTEXT}


