#!/bin/bash
[ "${debug}" = "true" ] && set -x

function hlp(){
echo adds texttv to model
}


function model(){
(hlp)
/bin/bash -e ${ELECSEE_SCRIPTS}/python
(cat << EOF
apt install -y ffmpeg ffmpeg-doc imagemagick git git-flow python3-venv
su -l -c 'git clone -b development https://github.com/gardsted/texttv' $USS
su -l -c 'cd texttv && python3 -m venv venv && venv/bin/pip install -r requirements.txt' $USS
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




function instance(){
(cat << EOF
su -l -c 'cd texttv && git pull && venv/bin/pip install -r requirements.txt --upgrade' $USS
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1

}


$CONTEXT

