#!/bin/bash
#export PRIVILEGED=True
[ "${debug}" = "true" ] && set -x

function hlp(){
cat << EOF
adds openvpn and openconnect to container
EOF
}

function model(){
[ "${debug}" = "true" ] && set -x
(hlp)
(cat << EOF
[ "${debug}" = "true" ] && set -x
mkdir /dev/net 
mknod /dev/net/tun c 10 200
chmod 666 /dev/net/tun
apt-get -y install openvpn openconnect
cp /usr/lib/systemd/system/openvpn-client@.service /etc/systemd/system/openvpn-client@.service
sed -i s/LimitNPROC/#LimitNPROC/ /etc/systemd/system/openvpn-client@.service
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
}




function instance(){
[ "${debug}" = "true" ] && set -x
(cat << EOF
[ "${debug}" = "true" ] && set -x
EOF
) | lxc-attach --name ${CONTAINER} >> ${logfile} 2>&1
echo 'lxc.mount.entry = /dev/net dev/net none bind,create=dir' >> .local/share/lxc/${CONTAINER}/config
echo 'lxc.mount.entry = /dev/net/tun dev/net/tun none bind,create=file' >> .local/share/lxc/${CONTAINER}/config
}




$CONTEXT
