#!/bin/bash
echo wait for container to start > /dev/stderr

(
cat << EOF
(
    while true
    do
        ping -c 1 linuxcontainers.org  && break
        sleep 1
    done 
)
EOF
) | sudo lxc-attach --name ${CONTAINER}
